import os

DEVICE_NAME = "BAYYTI-B1"
API_VERSION = "1.0.0"

SENSOR_READ_INTERVAL = 60

VALVE_GPIO_PIN = 17
RELAY_GPIO_PIN = 27
FLOW_SENSOR_PIN = 22
LEAK_SENSOR_PIN = 23

SOIL_MOISTURE_THRESHOLD = 30
LEAK_DETECTION_ENABLED = True
AUTO_IRRIGATION_ENABLED = True

MAX_IRRIGATION_DURATION = 1800

API_KEY_HEADER = "X-API-Key"
DEFAULT_API_KEY = "bayyti_demo_key_12345"

ENABLE_GPIO = os.environ.get('ENABLE_GPIO', 'false').lower() == 'true'

SOLAR_VOLTAGE_PIN = 0
BATTERY_VOLTAGE_PIN = 1

WEATHER_API_KEY = os.environ.get('WEATHER_API_KEY', '')
LOCATION_LAT = 33.5731
LOCATION_LON = -7.5898
